<?php

namespace yangshihe\fontawesome;

class FontIcon {

	/*

	    Setting up Font Awesome can be as simple as adding two lines of code to your website, or you can be a pro and customize the LESS yourself! Font Awesome even plays nicely with Bootstrap 3!

	    Use this method to get the default Font Awesome CSS.

	    Copy the entire font-awesome directory into your project.
	    In the <head> of your html, reference the location to your font-awesome.min.css.

	    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

	    Check out the examples to start using Font Awesome!

	*/

	/**
	 * @return Array
	 * @version 4.5
	 */
	public static function FontAwesome() {

		$arr = [];

		$arr['NewIcons'] = array(
			'bluetooth' => '<i class="fa fa-bluetooth"></i> bluetooth',
			'bluetooth-b' => '<i class="fa fa-bluetooth-b"></i> bluetooth-b',
			'codiepie' => '<i class="fa fa-codiepie"></i> codiepie',
			'credit-card-alt' => '<i class="fa fa-credit-card-alt"></i> credit-card-alt',
			'edge' => '<i class="fa fa-edge"></i> edge',
			'fort-awesome' => '<i class="fa fa-fort-awesome"></i> fort-awesome',
			'hashtag' => '<i class="fa fa-hashtag"></i> hashtag',
			'mixcloud' => '<i class="fa fa-mixcloud"></i> mixcloud',
			'modx' => '<i class="fa fa-modx"></i> modx',
			'pause-circle' => '<i class="fa fa-pause-circle"></i> pause-circle',
			'pause-circle-o' => '<i class="fa fa-pause-circle-o"></i> pause-circle-o',
			'percent' => '<i class="fa fa-percent"></i> percent',
			'product-hunt' => '<i class="fa fa-product-hunt"></i> product-hunt',
			'reddit-alien' => '<i class="fa fa-reddit-alien"></i> reddit-alien',
			'scribd' => '<i class="fa fa-scribd"></i> scribd',
			'shopping-bag' => '<i class="fa fa-shopping-bag"></i> shopping-bag',
			'shopping-basket' => '<i class="fa fa-shopping-basket"></i> shopping-basket',
			'stop-circle' => '<i class="fa fa-stop-circle"></i> stop-circle',
			'stop-circle-o' => '<i class="fa fa-stop-circle-o"></i> stop-circle-o',
			'usb' => '<i class="fa fa-usb"></i> usb',
			'heart' => '<i class="fa fa-heart"></i> heart',
			'heart-o' => '<i class="fa fa-heart-o"></i> heart-o',
			'weixin' => '<i class="fa fa-weixin"></i> weixin',
			'qq' => '<i class="fa fa-qq"></i> qq',
			'weibo' => '<i class="fa fa-weibo"></i> weibo',
			'git' => '<i class="fa fa-git"></i> git',
			'apple' => '<i class="fa fa-apple"></i> apple',
			'andriod' => '<i class="fa fa-andriod"></i> andriod',
			'html5' => '<i class="fa fa-html5"></i> html5',
			'windows' => '<i class="fa fa-windows"></i> windows',
			'edge' => '<i class="fa fa-edge"></i> edge',
			'google' => '<i class="fa fa-google"></i> google',
			'chrome' => '<i class="fa fa-chrome"></i> chrome',
			'github' => '<i class="fa fa-github"></i> github',
			'firefox' => '<i class="fa fa-firefox"></i> firefox',
		);

		$arr['WebApplication'] = array(
			'adjust' => '<i class="fa fa-adjust"></i> adjust',
			'anchor' => '<i class="fa fa-anchor"></i> anchor',
			'archive' => '<i class="fa fa-archive"></i> archive',
			'area-chart' => '<i class="fa fa-area-chart"></i> area-chart',
			'arrows' => '<i class="fa fa-arrows"></i> arrows',
			'arrows-h' => '<i class="fa fa-arrows-h"></i> arrows-h',
			'arrows-v' => '<i class="fa fa-arrows-v"></i> arrows-v',
			'asterisk' => '<i class="fa fa-asterisk"></i> asterisk',
			'at' => '<i class="fa fa-at"></i> at',
			'balance-scale' => '<i class="fa fa-balance-scale"></i> balance-scale',
			'ban' => '<i class="fa fa-ban"></i> ban',
			'bar-chart' => '<i class="fa fa-bar-chart"></i> bar-chart',
			'barcode' => '<i class="fa fa-barcode"></i> barcode',
			'bars' => '<i class="fa fa-bars"></i> bars',
			'battery-empty' => '<i class="fa fa-battery-empty"></i> battery-empty',
			'battery-full' => '<i class="fa fa-battery-full"></i> battery-full',
			'battery-half' => '<i class="fa fa-battery-half"></i> battery-half',
			'battery-quarter' => '<i class="fa fa-battery-quarter"></i> battery-quarter',
			'battery-three-quarters' => '<i class="fa fa-battery-three-quarters"></i> battery-three-quarters',
			'bed' => '<i class="fa fa-bed"></i> bed',
			'beer' => '<i class="fa fa-beer"></i> beer',
			'bell' => '<i class="fa fa-bell"></i> bell',
			'bell-o' => '<i class="fa fa-bell-o"></i> bell-o',
			'bell-slash' => '<i class="fa fa-bell-slash"></i> bell-slash',
			'bell-slash-o' => '<i class="fa fa-bell-slash-o"></i> bell-slash-o',
			'bicycle' => '<i class="fa fa-bicycle"></i> bicycle',
			'binoculars' => '<i class="fa fa-binoculars"></i> binoculars',
			'birthday-cake' => '<i class="fa fa-birthday-cake"></i> birthday-cake',
			'bluetooth' => '<i class="fa fa-bluetooth"></i> bluetooth',
			'bluetooth-b' => '<i class="fa fa-bluetooth-b"></i> bluetooth-b',
			'bolt' => '<i class="fa fa-bolt"></i> bolt',
			'bomb' => '<i class="fa fa-bomb"></i> bomb',
			'book' => '<i class="fa fa-book"></i> book',
			'bookmark' => '<i class="fa fa-bookmark"></i> bookmark',
			'bookmark-o' => '<i class="fa fa-bookmark-o"></i> bookmark-o',
			'briefcase' => '<i class="fa fa-briefcase"></i> briefcase',
			'bug' => '<i class="fa fa-bug"></i> bug',
			'building' => '<i class="fa fa-building"></i> building',
			'building-o' => '<i class="fa fa-building-o"></i> building-o',
			'bullhorn' => '<i class="fa fa-bullhorn"></i> bullhorn',
			'bullseye' => '<i class="fa fa-bullseye"></i> bullseye',
			'bus' => '<i class="fa fa-bus"></i> bus',
			'calculator' => '<i class="fa fa-calculator"></i> calculator',
			'calendar' => '<i class="fa fa-calendar"></i> calendar',
			'calendar-check-o' => '<i class="fa fa-calendar-check-o"></i> calendar-check-o',
			'calendar-minus-o' => '<i class="fa fa-calendar-minus-o"></i> calendar-minus-o',
			'calendar-o' => '<i class="fa fa-calendar-o"></i> calendar-o',
			'calendar-plus-o' => '<i class="fa fa-calendar-plus-o"></i> calendar-plus-o',
			'calendar-times-o' => '<i class="fa fa-calendar-times-o"></i> calendar-times-o',
			'camera' => '<i class="fa fa-camera"></i> camera',
			'camera-retro' => '<i class="fa fa-camera-retro"></i> camera-retro',
			'car' => '<i class="fa fa-car"></i> car',
			'caret-square-o-down' => '<i class="fa fa-caret-square-o-down"></i> caret-square-o-down',
			'caret-square-o-left' => '<i class="fa fa-caret-square-o-left"></i> caret-square-o-left',
			'caret-square-o-right' => '<i class="fa fa-caret-square-o-right"></i> caret-square-o-right',
			'caret-square-o-up' => '<i class="fa fa-caret-square-o-up"></i> caret-square-o-up',
			'cart-arrow-down' => '<i class="fa fa-cart-arrow-down"></i> cart-arrow-down',
			'cart-plus' => '<i class="fa fa-cart-plus"></i> cart-plus',
			'cc' => '<i class="fa fa-cc"></i> cc',
			'certificate' => '<i class="fa fa-certificate"></i> certificate',
			'check' => '<i class="fa fa-check"></i> check',
			'check-circle' => '<i class="fa fa-check-circle"></i> check-circle',
			'check-circle-o' => '<i class="fa fa-check-circle-o"></i> check-circle-o',
			'check-square' => '<i class="fa fa-check-square"></i> check-square',
			'check-square-o' => '<i class="fa fa-check-square-o"></i> check-square-o',
			'child' => '<i class="fa fa-child"></i> child',
			'circle' => '<i class="fa fa-circle"></i> circle',
			'circle-o' => '<i class="fa fa-circle-o"></i> circle-o',
			'circle-o-notch' => '<i class="fa fa-circle-o-notch"></i> circle-o-notch',
			'circle-thin' => '<i class="fa fa-circle-thin"></i> circle-thin',
			'clock-o' => '<i class="fa fa-clock-o"></i> clock-o',
			'clone' => '<i class="fa fa-clone"></i> clone',
			'cloud' => '<i class="fa fa-cloud"></i> cloud',
			'cloud-download' => '<i class="fa fa-cloud-download"></i> cloud-download',
			'cloud-upload' => '<i class="fa fa-cloud-upload"></i> cloud-upload',
			'code' => '<i class="fa fa-code"></i> code',
			'code-fork' => '<i class="fa fa-code-fork"></i> code-fork',
			'coffee' => '<i class="fa fa-coffee"></i> coffee',
			'cog' => '<i class="fa fa-cog"></i> cog',
			'cogs' => '<i class="fa fa-cogs"></i> cogs',
			'comment' => '<i class="fa fa-comment"></i> comment',
			'comment-o' => '<i class="fa fa-comment-o"></i> comment-o',
			'commenting' => '<i class="fa fa-commenting"></i> commenting',
			'commenting-o' => '<i class="fa fa-commenting-o"></i> commenting-o',
			'comments' => '<i class="fa fa-comments"></i> comments',
			'comments-o' => '<i class="fa fa-comments-o"></i> comments-o',
			'compass' => '<i class="fa fa-compass"></i> compass',
			'copyright' => '<i class="fa fa-copyright"></i> copyright',
			'creative-commons' => '<i class="fa fa-creative-commons"></i> creative-commons',
			'credit-card' => '<i class="fa fa-credit-card"></i> credit-card',
			'credit-card-alt' => '<i class="fa fa-credit-card-alt"></i> credit-card-alt',
			'crop' => '<i class="fa fa-crop"></i> crop',
			'crosshairs' => '<i class="fa fa-crosshairs"></i> crosshairs',
			'cube' => '<i class="fa fa-cube"></i> cube',
			'cubes' => '<i class="fa fa-cubes"></i> cubes',
			'cutlery' => '<i class="fa fa-cutlery"></i> cutlery',
			'database' => '<i class="fa fa-database"></i> database',
			'desktop' => '<i class="fa fa-desktop"></i> desktop',
			'diamond' => '<i class="fa fa-diamond"></i> diamond',
			'dot-circle-o' => '<i class="fa fa-dot-circle-o"></i> dot-circle-o',
			'download' => '<i class="fa fa-download"></i> download',
			'ellipsis-h' => '<i class="fa fa-ellipsis-h"></i> ellipsis-h',
			'ellipsis-v' => '<i class="fa fa-ellipsis-v"></i> ellipsis-v',
			'envelope' => '<i class="fa fa-envelope"></i> envelope',
			'envelope-o' => '<i class="fa fa-envelope-o"></i> envelope-o',
			'envelope-square' => '<i class="fa fa-envelope-square"></i> envelope-square',
			'eraser' => '<i class="fa fa-eraser"></i> eraser',
			'exchange' => '<i class="fa fa-exchange"></i> exchange',
			'exclamation' => '<i class="fa fa-exclamation"></i> exclamation',
			'exclamation-circle' => '<i class="fa fa-exclamation-circle"></i> exclamation-circle',
			'exclamation-triangle' => '<i class="fa fa-exclamation-triangle"></i> exclamation-triangle',
			'external-link' => '<i class="fa fa-external-link"></i> external-link',
			'external-link-square' => '<i class="fa fa-external-link-square"></i> external-link-square',
			'eye' => '<i class="fa fa-eye"></i> eye',
			'eye-slash' => '<i class="fa fa-eye-slash"></i> eye-slash',
			'eyedropper' => '<i class="fa fa-eyedropper"></i> eyedropper',
			'fax' => '<i class="fa fa-fax"></i> fax',
			'female' => '<i class="fa fa-female"></i> female',
			'fighter-jet' => '<i class="fa fa-fighter-jet"></i> fighter-jet',
			'file-archive-o' => '<i class="fa fa-file-archive-o"></i> file-archive-o',
			'file-audio-o' => '<i class="fa fa-file-audio-o"></i> file-audio-o',
			'file-code-o' => '<i class="fa fa-file-code-o"></i> file-code-o',
			'file-excel-o' => '<i class="fa fa-file-excel-o"></i> file-excel-o',
			'file-image-o' => '<i class="fa fa-file-image-o"></i> file-image-o',
			'file-pdf-o' => '<i class="fa fa-file-pdf-o"></i> file-pdf-o',
			'file-powerpoint-o' => '<i class="fa fa-file-powerpoint-o"></i> file-powerpoint-o',
			'file-video-o' => '<i class="fa fa-file-video-o"></i> file-video-o',
			'file-word-o' => '<i class="fa fa-file-word-o"></i> file-word-o',
			'film' => '<i class="fa fa-film"></i> film',
			'filter' => '<i class="fa fa-filter"></i> filter',
			'fire' => '<i class="fa fa-fire"></i> fire',
			'fire-extinguisher' => '<i class="fa fa-fire-extinguisher"></i> fire-extinguisher',
			'flag' => '<i class="fa fa-flag"></i> flag',
			'flag-checkered' => '<i class="fa fa-flag-checkered"></i> flag-checkered',
			'flag-o' => '<i class="fa fa-flag-o"></i> flag-o',
			'flask' => '<i class="fa fa-flask"></i> flask',
			'folder' => '<i class="fa fa-folder"></i> folder',
			'folder-o' => '<i class="fa fa-folder-o"></i> folder-o',
			'folder-open' => '<i class="fa fa-folder-open"></i> folder-open',
			'folder-open-o' => '<i class="fa fa-folder-open-o"></i> folder-open-o',
			'frown-o' => '<i class="fa fa-frown-o"></i> frown-o',
			'futbol-o' => '<i class="fa fa-futbol-o"></i> futbol-o',
			'gamepad' => '<i class="fa fa-gamepad"></i> gamepad',
			'gavel' => '<i class="fa fa-gavel"></i> gavel',
			'gift' => '<i class="fa fa-gift"></i> gift',
			'glass' => '<i class="fa fa-glass"></i> glass',
			'globe' => '<i class="fa fa-globe"></i> globe',
			'graduation-cap' => '<i class="fa fa-graduation-cap"></i> graduation-cap',
			'hand-lizard-o' => '<i class="fa fa-hand-lizard-o"></i> hand-lizard-o',
			'hand-paper-o' => '<i class="fa fa-hand-paper-o"></i> hand-paper-o',
			'hand-peace-o' => '<i class="fa fa-hand-peace-o"></i> hand-peace-o',
			'hand-pointer-o' => '<i class="fa fa-hand-pointer-o"></i> hand-pointer-o',
			'hand-rock-o' => '<i class="fa fa-hand-rock-o"></i> hand-rock-o',
			'hand-scissors-o' => '<i class="fa fa-hand-scissors-o"></i> hand-scissors-o',
			'hand-spock-o' => '<i class="fa fa-hand-spock-o"></i> hand-spock-o',
			'hashtag' => '<i class="fa fa-hashtag"></i> hashtag',
			'hdd-o' => '<i class="fa fa-hdd-o"></i> hdd-o',
			'headphones' => '<i class="fa fa-headphones"></i> headphones',
			'heart' => '<i class="fa fa-heart"></i> heart',
			'heart-o' => '<i class="fa fa-heart-o"></i> heart-o',
			'heartbeat' => '<i class="fa fa-heartbeat"></i> heartbeat',
			'history' => '<i class="fa fa-history"></i> history',
			'home' => '<i class="fa fa-home"></i> home',
			'hourglass' => '<i class="fa fa-hourglass"></i> hourglass',
			'hourglass-end' => '<i class="fa fa-hourglass-end"></i> hourglass-end',
			'hourglass-half' => '<i class="fa fa-hourglass-half"></i> hourglass-half',
			'hourglass-o' => '<i class="fa fa-hourglass-o"></i> hourglass-o',
			'hourglass-start' => '<i class="fa fa-hourglass-start"></i> hourglass-start',
			'i-cursor' => '<i class="fa fa-i-cursor"></i> i-cursor',
			'inbox' => '<i class="fa fa-inbox"></i> inbox',
			'industry' => '<i class="fa fa-industry"></i> industry',
			'info' => '<i class="fa fa-info"></i> info',
			'info-circle' => '<i class="fa fa-info-circle"></i> info-circle',
			'key' => '<i class="fa fa-key"></i> key',
			'keyboard-o' => '<i class="fa fa-keyboard-o"></i> keyboard-o',
			'language' => '<i class="fa fa-language"></i> language',
			'laptop' => '<i class="fa fa-laptop"></i> laptop',
			'leaf' => '<i class="fa fa-leaf"></i> leaf',
			'lemon-o' => '<i class="fa fa-lemon-o"></i> lemon-o',
			'level-down' => '<i class="fa fa-level-down"></i> level-down',
			'level-up' => '<i class="fa fa-level-up"></i> level-up',
			'life-ring' => '<i class="fa fa-life-ring"></i> life-ring',
			'lightbulb-o' => '<i class="fa fa-lightbulb-o"></i> lightbulb-o',
			'line-chart' => '<i class="fa fa-line-chart"></i> line-chart',
			'location-arrow' => '<i class="fa fa-location-arrow"></i> location-arrow',
			'lock' => '<i class="fa fa-lock"></i> lock',
			'magic' => '<i class="fa fa-magic"></i> magic',
			'magnet' => '<i class="fa fa-magnet"></i> magnet',
			'male' => '<i class="fa fa-male"></i> male',
			'map' => '<i class="fa fa-map"></i> map',
			'map-marker' => '<i class="fa fa-map-marker"></i> map-marker',
			'map-o' => '<i class="fa fa-map-o"></i> map-o',
			'map-pin' => '<i class="fa fa-map-pin"></i> map-pin',
			'map-signs' => '<i class="fa fa-map-signs"></i> map-signs',
			'meh-o' => '<i class="fa fa-meh-o"></i> meh-o',
			'microphone' => '<i class="fa fa-microphone"></i> microphone',
			'microphone-slash' => '<i class="fa fa-microphone-slash"></i> microphone-slash',
			'minus' => '<i class="fa fa-minus"></i> minus',
			'minus-circle' => '<i class="fa fa-minus-circle"></i> minus-circle',
			'minus-square' => '<i class="fa fa-minus-square"></i> minus-square',
			'minus-square-o' => '<i class="fa fa-minus-square-o"></i> minus-square-o',
			'mobile' => '<i class="fa fa-mobile"></i> mobile',
			'money' => '<i class="fa fa-money"></i> money',
			'moon-o' => '<i class="fa fa-moon-o"></i> moon-o',
			'motorcycle' => '<i class="fa fa-motorcycle"></i> motorcycle',
			'mouse-pointer' => '<i class="fa fa-mouse-pointer"></i> mouse-pointer',
			'music' => '<i class="fa fa-music"></i> music',
			'newspaper-o' => '<i class="fa fa-newspaper-o"></i> newspaper-o',
			'object-group' => '<i class="fa fa-object-group"></i> object-group',
			'object-ungroup' => '<i class="fa fa-object-ungroup"></i> object-ungroup',
			'paint-brush' => '<i class="fa fa-paint-brush"></i> paint-brush',
			'paper-plane' => '<i class="fa fa-paper-plane"></i> paper-plane',
			'paper-plane-o' => '<i class="fa fa-paper-plane-o"></i> paper-plane-o',
			'paw' => '<i class="fa fa-paw"></i> paw',
			'pencil' => '<i class="fa fa-pencil"></i> pencil',
			'pencil-square' => '<i class="fa fa-pencil-square"></i> pencil-square',
			'pencil-square-o' => '<i class="fa fa-pencil-square-o"></i> pencil-square-o',
			'percent' => '<i class="fa fa-percent"></i> percent',
			'phone' => '<i class="fa fa-phone"></i> phone',
			'phone-square' => '<i class="fa fa-phone-square"></i> phone-square',
			'picture-o' => '<i class="fa fa-picture-o"></i> picture-o',
			'pie-chart' => '<i class="fa fa-pie-chart"></i> pie-chart',
			'plane' => '<i class="fa fa-plane"></i> plane',
			'plug' => '<i class="fa fa-plug"></i> plug',
			'plus' => '<i class="fa fa-plus"></i> plus',
			'plus-circle' => '<i class="fa fa-plus-circle"></i> plus-circle',
			'plus-square' => '<i class="fa fa-plus-square"></i> plus-square',
			'plus-square-o' => '<i class="fa fa-plus-square-o"></i> plus-square-o',
			'power-off' => '<i class="fa fa-power-off"></i> power-off',
			'print' => '<i class="fa fa-print"></i> print',
			'puzzle-piece' => '<i class="fa fa-puzzle-piece"></i> puzzle-piece',
			'qrcode' => '<i class="fa fa-qrcode"></i> qrcode',
			'question' => '<i class="fa fa-question"></i> question',
			'question-circle' => '<i class="fa fa-question-circle"></i> question-circle',
			'quote-left' => '<i class="fa fa-quote-left"></i> quote-left',
			'quote-right' => '<i class="fa fa-quote-right"></i> quote-right',
			'random' => '<i class="fa fa-random"></i> random',
			'recycle' => '<i class="fa fa-recycle"></i> recycle',
			'refresh' => '<i class="fa fa-refresh"></i> refresh',
			'registered' => '<i class="fa fa-registered"></i> registered',
			'reply' => '<i class="fa fa-reply"></i> reply',
			'reply-all' => '<i class="fa fa-reply-all"></i> reply-all',
			'retweet' => '<i class="fa fa-retweet"></i> retweet',
			'road' => '<i class="fa fa-road"></i> road',
			'rocket' => '<i class="fa fa-rocket"></i> rocket',
			'rss' => '<i class="fa fa-rss"></i> rss',
			'rss-square' => '<i class="fa fa-rss-square"></i> rss-square',
			'search' => '<i class="fa fa-search"></i> search',
			'search-minus' => '<i class="fa fa-search-minus"></i> search-minus',
			'search-plus' => '<i class="fa fa-search-plus"></i> search-plus',
			'server' => '<i class="fa fa-server"></i> server',
			'share' => '<i class="fa fa-share"></i> share',
			'share-alt' => '<i class="fa fa-share-alt"></i> share-alt',
			'share-alt-square' => '<i class="fa fa-share-alt-square"></i> share-alt-square',
			'share-square' => '<i class="fa fa-share-square"></i> share-square',
			'share-square-o' => '<i class="fa fa-share-square-o"></i> share-square-o',
			'shield' => '<i class="fa fa-shield"></i> shield',
			'ship' => '<i class="fa fa-ship"></i> ship',
			'shopping-bag' => '<i class="fa fa-shopping-bag"></i> shopping-bag',
			'shopping-basket' => '<i class="fa fa-shopping-basket"></i> shopping-basket',
			'shopping-cart' => '<i class="fa fa-shopping-cart"></i> shopping-cart',
			'sign-in' => '<i class="fa fa-sign-in"></i> sign-in',
			'sign-out' => '<i class="fa fa-sign-out"></i> sign-out',
			'signal' => '<i class="fa fa-signal"></i> signal',
			'sitemap' => '<i class="fa fa-sitemap"></i> sitemap',
			'sliders' => '<i class="fa fa-sliders"></i> sliders',
			'smile-o' => '<i class="fa fa-smile-o"></i> smile-o',
			'sort' => '<i class="fa fa-sort"></i> sort',
			'sort-alpha-asc' => '<i class="fa fa-sort-alpha-asc"></i> sort-alpha-asc',
			'sort-alpha-desc' => '<i class="fa fa-sort-alpha-desc"></i> sort-alpha-desc',
			'sort-amount-asc' => '<i class="fa fa-sort-amount-asc"></i> sort-amount-asc',
			'sort-amount-desc' => '<i class="fa fa-sort-amount-desc"></i> sort-amount-desc',
			'sort-asc' => '<i class="fa fa-sort-asc"></i> sort-asc',
			'sort-desc' => '<i class="fa fa-sort-desc"></i> sort-desc',
			'sort-numeric-asc' => '<i class="fa fa-sort-numeric-asc"></i> sort-numeric-asc',
			'sort-numeric-desc' => '<i class="fa fa-sort-numeric-desc"></i> sort-numeric-desc',
			'space-shuttle' => '<i class="fa fa-space-shuttle"></i> space-shuttle',
			'spinner' => '<i class="fa fa-spinner"></i> spinner',
			'spoon' => '<i class="fa fa-spoon"></i> spoon',
			'square' => '<i class="fa fa-square"></i> square',
			'square-o' => '<i class="fa fa-square-o"></i> square-o',
			'star' => '<i class="fa fa-star"></i> star',
			'star-half' => '<i class="fa fa-star-half"></i> star-half',
			'star-half-o' => '<i class="fa fa-star-half-o"></i> star-half-o',
			'star-o' => '<i class="fa fa-star-o"></i> star-o',
			'sticky-note' => '<i class="fa fa-sticky-note"></i> sticky-note',
			'sticky-note-o' => '<i class="fa fa-sticky-note-o"></i> sticky-note-o',
			'street-view' => '<i class="fa fa-street-view"></i> street-view',
			'suitcase' => '<i class="fa fa-suitcase"></i> suitcase',
			'sun-o' => '<i class="fa fa-sun-o"></i> sun-o',
			'tablet' => '<i class="fa fa-tablet"></i> tablet',
			'tachometer' => '<i class="fa fa-tachometer"></i> tachometer',
			'tag' => '<i class="fa fa-tag"></i> tag',
			'tags' => '<i class="fa fa-tags"></i> tags',
			'tasks' => '<i class="fa fa-tasks"></i> tasks',
			'taxi' => '<i class="fa fa-taxi"></i> taxi',
			'television' => '<i class="fa fa-television"></i> television',
			'terminal' => '<i class="fa fa-terminal"></i> terminal',
			'thumb-tack' => '<i class="fa fa-thumb-tack"></i> thumb-tack',
			'thumbs-down' => '<i class="fa fa-thumbs-down"></i> thumbs-down',
			'thumbs-o-down' => '<i class="fa fa-thumbs-o-down"></i> thumbs-o-down',
			'thumbs-o-up' => '<i class="fa fa-thumbs-o-up"></i> thumbs-o-up',
			'thumbs-up' => '<i class="fa fa-thumbs-up"></i> thumbs-up',
			'ticket' => '<i class="fa fa-ticket"></i> ticket',
			'times' => '<i class="fa fa-times"></i> times',
			'times-circle' => '<i class="fa fa-times-circle"></i> times-circle',
			'times-circle-o' => '<i class="fa fa-times-circle-o"></i> times-circle-o',
			'tint' => '<i class="fa fa-tint"></i> tint',
			'toggle-off' => '<i class="fa fa-toggle-off"></i> toggle-off',
			'toggle-on' => '<i class="fa fa-toggle-on"></i> toggle-on',
			'trademark' => '<i class="fa fa-trademark"></i> trademark',
			'trash' => '<i class="fa fa-trash"></i> trash',
			'trash-o' => '<i class="fa fa-trash-o"></i> trash-o',
			'tree' => '<i class="fa fa-tree"></i> tree',
			'trophy' => '<i class="fa fa-trophy"></i> trophy',
			'truck' => '<i class="fa fa-truck"></i> truck',
			'tty' => '<i class="fa fa-tty"></i> tty',
			'umbrella' => '<i class="fa fa-umbrella"></i> umbrella',
			'university' => '<i class="fa fa-university"></i> university',
			'unlock' => '<i class="fa fa-unlock"></i> unlock',
			'unlock-alt' => '<i class="fa fa-unlock-alt"></i> unlock-alt',
			'upload' => '<i class="fa fa-upload"></i> upload',
			'user' => '<i class="fa fa-user"></i> user',
			'user-plus' => '<i class="fa fa-user-plus"></i> user-plus',
			'user-secret' => '<i class="fa fa-user-secret"></i> user-secret',
			'user-times' => '<i class="fa fa-user-times"></i> user-times',
			'users' => '<i class="fa fa-users"></i> users',
			'video-camera' => '<i class="fa fa-video-camera"></i> video-camera',
			'volume-down' => '<i class="fa fa-volume-down"></i> volume-down',
			'volume-off' => '<i class="fa fa-volume-off"></i> volume-off',
			'volume-up' => '<i class="fa fa-volume-up"></i> volume-up',
			'wheelchair' => '<i class="fa fa-wheelchair"></i> wheelchair',
			'wifi' => '<i class="fa fa-wifi"></i> wifi',
			'wrench' => '<i class="fa fa-wrench"></i> wrench',
		);

		$arr['Hand'] = array(
			'hand-lizard-o' => '<i class="fa fa-hand-lizard-o"></i> hand-lizard-o',
			'hand-o-down' => '<i class="fa fa-hand-o-down"></i> hand-o-down',
			'hand-o-left' => '<i class="fa fa-hand-o-left"></i> hand-o-left',
			'hand-o-right' => '<i class="fa fa-hand-o-right"></i> hand-o-right',
			'hand-o-up' => '<i class="fa fa-hand-o-up"></i> hand-o-up',
			'hand-paper-o' => '<i class="fa fa-hand-paper-o"></i> hand-paper-o',
			'hand-peace-o' => '<i class="fa fa-hand-peace-o"></i> hand-peace-o',
			'hand-pointer-o' => '<i class="fa fa-hand-pointer-o"></i> hand-pointer-o',
			'hand-rock-o' => '<i class="fa fa-hand-rock-o"></i> hand-rock-o',
			'hand-scissors-o' => '<i class="fa fa-hand-scissors-o"></i> hand-scissors-o',
			'hand-spock-o' => '<i class="fa fa-hand-spock-o"></i> hand-spock-o',
			'thumbs-down' => '<i class="fa fa-thumbs-down"></i> thumbs-down',
			'thumbs-o-down' => '<i class="fa fa-thumbs-o-down"></i> thumbs-o-down',
			'thumbs-o-up' => '<i class="fa fa-thumbs-o-up"></i> thumbs-o-up',
			'thumbs-up' => '<i class="fa fa-thumbs-up"></i> thumbs-up',
		);

		$arr['Transportation'] = array(
			'ambulance' => '<i class="fa fa-ambulance"></i> ambulance',
			'bicycle' => '<i class="fa fa-bicycle"></i> bicycle',
			'bus' => '<i class="fa fa-bus"></i> bus',
			'car' => '<i class="fa fa-car"></i> car',
			'fighter-jet' => '<i class="fa fa-fighter-jet"></i> fighter-jet',
			'motorcycle' => '<i class="fa fa-motorcycle"></i> motorcycle',
			'plane' => '<i class="fa fa-plane"></i> plane',
			'rocket' => '<i class="fa fa-rocket"></i> rocket',
			'ship' => '<i class="fa fa-ship"></i> ship',
			'space-shuttle' => '<i class="fa fa-space-shuttle"></i> space-shuttle',
			'subway' => '<i class="fa fa-subway"></i> subway',
			'taxi' => '<i class="fa fa-taxi"></i> taxi',
			'train' => '<i class="fa fa-train"></i> train',
			'truck' => '<i class="fa fa-truck"></i> truck',
			'wheelchair' => '<i class="fa fa-wheelchair"></i> wheelchair',
		);

		$arr['Gender'] = array(
			'genderless' => '<i class="fa fa-genderless"></i> genderless',
			'mars' => '<i class="fa fa-mars"></i> mars',
			'mars-double' => '<i class="fa fa-mars-double"></i> mars-double',
			'mars-stroke' => '<i class="fa fa-mars-stroke"></i> mars-stroke',
			'mars-stroke-h' => '<i class="fa fa-mars-stroke-h"></i> mars-stroke-h',
			'mars-stroke-v' => '<i class="fa fa-mars-stroke-v"></i> mars-stroke-v',
			'mercury' => '<i class="fa fa-mercury"></i> mercury',
			'neuter' => '<i class="fa fa-neuter"></i> neuter',
			'transgender' => '<i class="fa fa-transgender"></i> transgender',
			'transgender-alt' => '<i class="fa fa-transgender-alt"></i> transgender-alt',
			'venus' => '<i class="fa fa-venus"></i> venus',
			'venus-double' => '<i class="fa fa-venus-double"></i> venus-double',
			'venus-mars' => '<i class="fa fa-venus-mars"></i> venus-mars',
		);

		$arr['File'] = array(
			'file' => '<i class="fa fa-file"></i> file',
			'file-archive-o' => '<i class="fa fa-file-archive-o"></i> file-archive-o',
			'file-audio-o' => '<i class="fa fa-file-audio-o"></i> file-audio-o',
			'file-code-o' => '<i class="fa fa-file-code-o"></i> file-code-o',
			'file-excel-o' => '<i class="fa fa-file-excel-o"></i> file-excel-o',
			'file-image-o' => '<i class="fa fa-file-image-o"></i> file-image-o',
			'file-o' => '<i class="fa fa-file-o"></i> file-o',
			'file-pdf-o' => '<i class="fa fa-file-pdf-o"></i> file-pdf-o',
			'file-powerpoint-o' => '<i class="fa fa-file-powerpoint-o"></i> file-powerpoint-o',
			'file-text' => '<i class="fa fa-file-text"></i> file-text',
			'file-text-o' => '<i class="fa fa-file-text-o"></i> file-text-o',
			'file-video-o' => '<i class="fa fa-file-video-o"></i> file-video-o',
			'file-word-o' => '<i class="fa fa-file-word-o"></i> file-word-o',
		);

		$arr['Spinner'] = array(
			'circle-o-notch' => '<i class="fa fa-circle-o-notch"></i> circle-o-notch',
			'cog' => '<i class="fa fa-cog"></i> cog',
			'refresh' => '<i class="fa fa-refresh"></i> refresh',
			'spinner' => '<i class="fa fa-spinner"></i> spinner',
		);

		$arr['FormControl'] = array(
			'check-square' => '<i class="fa fa-check-square"></i> check-square',
			'check-square-o' => '<i class="fa fa-check-square-o"></i> check-square-o',
			'circle' => '<i class="fa fa-circle"></i> circle',
			'circle-o' => '<i class="fa fa-circle-o"></i> circle-o',
			'dot-circle-o' => '<i class="fa fa-dot-circle-o"></i> dot-circle-o',
			'minus-square' => '<i class="fa fa-minus-square"></i> minus-square',
			'minus-square-o' => '<i class="fa fa-minus-square-o"></i> minus-square-o',
			'plus-square' => '<i class="fa fa-plus-square"></i> plus-square',
			'plus-square-o' => '<i class="fa fa-plus-square-o"></i> plus-square-o',
			'square' => '<i class="fa fa-square"></i> square',
			'square-o' => '<i class="fa fa-square-o"></i> square-o',
		);

		$arr['Payment'] = array(
			'cc-amex' => '<i class="fa fa-cc-amex"></i> cc-amex',
			'cc-diners-club' => '<i class="fa fa-cc-diners-club"></i> cc-diners-club',
			'cc-discover' => '<i class="fa fa-cc-discover"></i> cc-discover',
			'cc-jcb' => '<i class="fa fa-cc-jcb"></i> cc-jcb',
			'cc-mastercard' => '<i class="fa fa-cc-mastercard"></i> cc-mastercard',
			'cc-paypal' => '<i class="fa fa-cc-paypal"></i> cc-paypal',
			'cc-stripe' => '<i class="fa fa-cc-stripe"></i> cc-stripe',
			'cc-visa' => '<i class="fa fa-cc-visa"></i> cc-visa',
			'credit-card' => '<i class="fa fa-credit-card"></i> credit-card',
			'credit-card-alt' => '<i class="fa fa-credit-card-alt"></i> credit-card-alt',
			'google-wallet' => '<i class="fa fa-google-wallet"></i> google-wallet',
			'paypal' => '<i class="fa fa-paypal"></i> paypal',
		);

		$arr['Chart'] = array(
			'area-chart' => '<i class="fa fa-area-chart"></i> area-chart',
			'bar-chart' => '<i class="fa fa-bar-chart"></i> bar-chart',
			'line-chart' => '<i class="fa fa-line-chart"></i> line-chart',
			'pie-chart' => '<i class="fa fa-pie-chart"></i> pie-chart',
		);

		$arr['Currency'] = array(
			'btc' => '<i class="fa fa-btc"></i> btc',
			'eur' => '<i class="fa fa-eur"></i> eur',
			'gbp' => '<i class="fa fa-gbp"></i> gbp',
			'gg' => '<i class="fa fa-gg"></i> gg',
			'gg-circle' => '<i class="fa fa-gg-circle"></i> gg-circle',
			'ils' => '<i class="fa fa-ils"></i> ils',
			'inr' => '<i class="fa fa-inr"></i> inr',
			'jpy' => '<i class="fa fa-jpy"></i> jpy',
			'krw' => '<i class="fa fa-krw"></i> krw',
			'money' => '<i class="fa fa-money"></i> money',
			'rub' => '<i class="fa fa-rub"></i> rub',
			'try' => '<i class="fa fa-try"></i> try',
			'usd' => '<i class="fa fa-usd"></i> usd',
		);

		$arr['TextEditor'] = array(
			'align-center' => '<i class="fa fa-align-center"></i> align-center',
			'align-justify' => '<i class="fa fa-align-justify"></i> align-justify',
			'align-left' => '<i class="fa fa-align-left"></i> align-left',
			'align-right' => '<i class="fa fa-align-right"></i> align-right',
			'bold' => '<i class="fa fa-bold"></i> bold',
			'chain-broken' => '<i class="fa fa-chain-broken"></i> chain-broken',
			'clipboard' => '<i class="fa fa-clipboard"></i> clipboard',
			'columns' => '<i class="fa fa-columns"></i> columns',
			'eraser' => '<i class="fa fa-eraser"></i> eraser',
			'file' => '<i class="fa fa-file"></i> file',
			'file-o' => '<i class="fa fa-file-o"></i> file-o',
			'file-text' => '<i class="fa fa-file-text"></i> file-text',
			'file-text-o' => '<i class="fa fa-file-text-o"></i> file-text-o',
			'files-o' => '<i class="fa fa-files-o"></i> files-o',
			'floppy-o' => '<i class="fa fa-floppy-o"></i> floppy-o',
			'font' => '<i class="fa fa-font"></i> font',
			'header' => '<i class="fa fa-header"></i> header',
			'indent' => '<i class="fa fa-indent"></i> indent',
			'italic' => '<i class="fa fa-italic"></i> italic',
			'link' => '<i class="fa fa-link"></i> link',
			'list' => '<i class="fa fa-list"></i> list',
			'list-alt' => '<i class="fa fa-list-alt"></i> list-alt',
			'list-ol' => '<i class="fa fa-list-ol"></i> list-ol',
			'list-ul' => '<i class="fa fa-list-ul"></i> list-ul',
			'outdent' => '<i class="fa fa-outdent"></i> outdent',
			'paperclip' => '<i class="fa fa-paperclip"></i> paperclip',
			'paragraph' => '<i class="fa fa-paragraph"></i> paragraph',
			'repeat' => '<i class="fa fa-repeat"></i> repeat',
			'scissors' => '<i class="fa fa-scissors"></i> scissors',
			'strikethrough' => '<i class="fa fa-strikethrough"></i> strikethrough',
			'subscript' => '<i class="fa fa-subscript"></i> subscript',
			'superscript' => '<i class="fa fa-superscript"></i> superscript',
			'table' => '<i class="fa fa-table"></i> table',
			'text-height' => '<i class="fa fa-text-height"></i> text-height',
			'text-width' => '<i class="fa fa-text-width"></i> text-width',
			'th' => '<i class="fa fa-th"></i> th',
			'th-large' => '<i class="fa fa-th-large"></i> th-large',
			'th-list' => '<i class="fa fa-th-list"></i> th-list',
			'underline' => '<i class="fa fa-underline"></i> underline',
			'undo' => '<i class="fa fa-undo"></i> undo',
		);

		$arr['Directional'] = array(
			'angle-double-down' => '<i class="fa fa-angle-double-down"></i> angle-double-down',
			'angle-double-left' => '<i class="fa fa-angle-double-left"></i> angle-double-left',
			'angle-double-right' => '<i class="fa fa-angle-double-right"></i> angle-double-right',
			'angle-double-up' => '<i class="fa fa-angle-double-up"></i> angle-double-up',
			'angle-down' => '<i class="fa fa-angle-down"></i> angle-down',
			'angle-left' => '<i class="fa fa-angle-left"></i> angle-left',
			'angle-right' => '<i class="fa fa-angle-right"></i> angle-right',
			'angle-up' => '<i class="fa fa-angle-up"></i> angle-up',
			'arrow-circle-down' => '<i class="fa fa-arrow-circle-down"></i> arrow-circle-down',
			'arrow-circle-left' => '<i class="fa fa-arrow-circle-left"></i> arrow-circle-left',
			'arrow-circle-o-down' => '<i class="fa fa-arrow-circle-o-down"></i> arrow-circle-o-down',
			'arrow-circle-o-left' => '<i class="fa fa-arrow-circle-o-left"></i> arrow-circle-o-left',
			'arrow-circle-o-right' => '<i class="fa fa-arrow-circle-o-right"></i> arrow-circle-o-right',
			'arrow-circle-o-up' => '<i class="fa fa-arrow-circle-o-up"></i> arrow-circle-o-up',
			'arrow-circle-right' => '<i class="fa fa-arrow-circle-right"></i> arrow-circle-right',
			'arrow-circle-up' => '<i class="fa fa-arrow-circle-up"></i> arrow-circle-up',
			'arrow-down' => '<i class="fa fa-arrow-down"></i> arrow-down',
			'arrow-left' => '<i class="fa fa-arrow-left"></i> arrow-left',
			'arrow-right' => '<i class="fa fa-arrow-right"></i> arrow-right',
			'arrow-up' => '<i class="fa fa-arrow-up"></i> arrow-up',
			'arrows' => '<i class="fa fa-arrows"></i> arrows',
			'arrows-alt' => '<i class="fa fa-arrows-alt"></i> arrows-alt',
			'arrows-h' => '<i class="fa fa-arrows-h"></i> arrows-h',
			'arrows-v' => '<i class="fa fa-arrows-v"></i> arrows-v',
			'caret-down' => '<i class="fa fa-caret-down"></i> caret-down',
			'caret-left' => '<i class="fa fa-caret-left"></i> caret-left',
			'caret-right' => '<i class="fa fa-caret-right"></i> caret-right',
			'caret-square-o-down' => '<i class="fa fa-caret-square-o-down"></i> caret-square-o-down',
			'caret-square-o-left' => '<i class="fa fa-caret-square-o-left"></i> caret-square-o-left',
			'caret-square-o-right' => '<i class="fa fa-caret-square-o-right"></i> caret-square-o-right',
			'caret-square-o-up' => '<i class="fa fa-caret-square-o-up"></i> caret-square-o-up',
			'caret-up' => '<i class="fa fa-caret-up"></i> caret-up',
			'chevron-circle-down' => '<i class="fa fa-chevron-circle-down"></i> chevron-circle-down',
			'chevron-circle-left' => '<i class="fa fa-chevron-circle-left"></i> chevron-circle-left',
			'chevron-circle-right' => '<i class="fa fa-chevron-circle-right"></i> chevron-circle-right',
			'chevron-circle-up' => '<i class="fa fa-chevron-circle-up"></i> chevron-circle-up',
			'chevron-down' => '<i class="fa fa-chevron-down"></i> chevron-down',
			'chevron-left' => '<i class="fa fa-chevron-left"></i> chevron-left',
			'chevron-right' => '<i class="fa fa-chevron-right"></i> chevron-right',
			'chevron-up' => '<i class="fa fa-chevron-up"></i> chevron-up',
			'exchange' => '<i class="fa fa-exchange"></i> exchange',
			'hand-o-down' => '<i class="fa fa-hand-o-down"></i> hand-o-down',
			'hand-o-left' => '<i class="fa fa-hand-o-left"></i> hand-o-left',
			'hand-o-right' => '<i class="fa fa-hand-o-right"></i> hand-o-right',
			'hand-o-up' => '<i class="fa fa-hand-o-up"></i> hand-o-up',
			'long-arrow-down' => '<i class="fa fa-long-arrow-down"></i> long-arrow-down',
			'long-arrow-left' => '<i class="fa fa-long-arrow-left"></i> long-arrow-left',
			'long-arrow-right' => '<i class="fa fa-long-arrow-right"></i> long-arrow-right',
			'long-arrow-up' => '<i class="fa fa-long-arrow-up"></i> long-arrow-up',
		);

		$arr['Video'] = array(
			'arrows-alt' => '<i class="fa fa-arrows-alt"></i> arrows-alt',
			'backward' => '<i class="fa fa-backward"></i> backward',
			'compress' => '<i class="fa fa-compress"></i> compress',
			'eject' => '<i class="fa fa-eject"></i> eject',
			'expand' => '<i class="fa fa-expand"></i> expand',
			'fast-backward' => '<i class="fa fa-fast-backward"></i> fast-backward',
			'fast-forward' => '<i class="fa fa-fast-forward"></i> fast-forward',
			'forward' => '<i class="fa fa-forward"></i> forward',
			'pause' => '<i class="fa fa-pause"></i> pause',
			'pause-circle' => '<i class="fa fa-pause-circle"></i> pause-circle',
			'pause-circle-o' => '<i class="fa fa-pause-circle-o"></i> pause-circle-o',
			'play' => '<i class="fa fa-play"></i> play',
			'play-circle' => '<i class="fa fa-play-circle"></i> play-circle',
			'play-circle-o' => '<i class="fa fa-play-circle-o"></i> play-circle-o',
			'random' => '<i class="fa fa-random"></i> random',
			'step-backward' => '<i class="fa fa-step-backward"></i> step-backward',
			'step-forward' => '<i class="fa fa-step-forward"></i> step-forward',
			'stop' => '<i class="fa fa-stop"></i> stop',
			'stop-circle' => '<i class="fa fa-stop-circle"></i> stop-circle',
			'stop-circle-o' => '<i class="fa fa-stop-circle-o"></i> stop-circle-o',
			'youtube-play' => '<i class="fa fa-youtube-play"></i> youtube-play',
		);

		return $arr;
	}

}
